import mongoose, { Schema, Document } from "mongoose";

export interface ITripQuery extends Document {
  customerName: string;
  customerEmail: string;
  destinations: string[];
  duration: string;
  accommodation: string;
  travelVision: string;
  status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
  aiGeneratedQuote?: string; // HTML string snippet generated by Groq Llama 3
  isEmailedToUser: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TripQuerySchema: Schema = new Schema(
  {
    customerName: { type: String, required: true },
    customerEmail: { type: String, required: true },
    destinations: { type: [String], default: [] },
    duration: { type: String, default: "" },
    accommodation: { type: String, default: "" },
    travelVision: { type: String, default: "" },
    status: {
      type: String,
      enum: ["PENDING", "PROCESSING", "COMPLETED", "FAILED"],
      default: "PENDING",
    },
    aiGeneratedQuote: { type: String },
    isEmailedToUser: { type: Boolean, default: false },
  },
  {
    timestamps: true, // Automatically manages createdAt and updatedAt
  }
);

// Prevent Next.js HMR (Hot Module Replacement) from recompiling the model continuously
const TripQuery = mongoose.models.TripQuery || mongoose.model<ITripQuery>("TripQuery", TripQuerySchema);

export default TripQuery;
